const TEST_ID = 9;

export const demoQuestions = [
  {
    testId: TEST_ID,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "Hello, what ___ your name?",
    options: JSON.stringify(["is", "am", "are", "be"]),
    correctAnswer: "is",
    explanation: "Birlik uchinchi shaxs uchun 'is' ishlatiladi.",
    points: 1,
    difficulty: 1,
    skill: "Grammar",
    isActive: true,
  },
  {
    testId: TEST_ID,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "I ___ from Uzbekistan.",
    options: JSON.stringify(["is", "am", "are", "be"]),
    correctAnswer: "am",
    explanation: "'I' (men) olmoshi uchun 'am' to'g'ri bog'lovchidir.",
    points: 1,
    difficulty: 1,
    skill: "Grammar",
    isActive: true,
  },
  {
    testId: TEST_ID,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "They ___ playing football now.",
    options: JSON.stringify(["is", "am", "are", "was"]),
    correctAnswer: "are",
    explanation: "Ko'plik uchun hozirgi davom zamonda 'are' ishlatiladi.",
    points: 1,
    difficulty: 1,
    skill: "Grammar",
    isActive: true,
  },
  {
    testId: TEST_ID,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "She ___ a doctor. She works in a hospital.",
    options: JSON.stringify(["is", "am", "are", "were"]),
    correctAnswer: "is",
    explanation: "Uchinchi shaxs birlik uchun hozirgi zamonda 'is' ishlatiladi.",
    points: 1,
    difficulty: 1,
    skill: "Vocabulary",
    isActive: true,
  },
  {
    testId: TEST_ID,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "How ___ is this book?",
    options: JSON.stringify(["many", "much", "old", "long"]),
    correctAnswer: "much",
    explanation: "Narxni so'rashda 'How much' iborasi ishlatiladi.",
    points: 1,
    difficulty: 1,
    skill: "Grammar",
    isActive: true,
  },
  {
    testId: TEST_ID,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "We ___ to the cinema yesterday.",
    options: JSON.stringify(["go", "gone", "went", "going"]),
    correctAnswer: "went",
    explanation: "O'tgan zamondagi tugallangan harakat uchun 'went' (Past Simple) ishlatiladi.",
    points: 1,
    difficulty: 1,
    skill: "Grammar",
    isActive: true,
  },
  {
    testId: TEST_ID,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "This is ___ apple.",
    options: JSON.stringify(["a", "an", "the", "–"]),
    correctAnswer: "an",
    explanation: "Unli tovush ('a') bilan boshlangan so'zdan oldin 'an' artikli ishlatiladi.",
    points: 1,
    difficulty: 1,
    skill: "Grammar",
    isActive: true,
  },
  {
    testId: TEST_ID,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "He ___ like milk. He prefers tea.",
    options: JSON.stringify(["don't", "doesn't", "isn't", "hasn't"]),
    correctAnswer: "doesn't",
    explanation: "He/She/It uchun inkor shaklda 'doesn't' ishlatiladi.",
    points: 1,
    difficulty: 1,
    skill: "Grammar",
    isActive: true,
  },
  {
    testId: TEST_ID,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "Which is the ___ city in the world?",
    options: JSON.stringify(["bigger", "biggest", "big", "most big"]),
    correctAnswer: "biggest",
    explanation: "Eng ustunlik darajasini yasash uchun '-est' qo'shimchasi ishdatiladi.",
    points: 1,
    difficulty: 1,
    skill: "Grammar",
    isActive: true,
  },
  {
    testId: TEST_ID,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "Can you ___ English?",
    options: JSON.stringify(["speak", "speaks", "speaking", "to speak"]),
    correctAnswer: "speak",
    explanation: "'Can' modal fe'lidan keyin fe'lning asil ko'rinishi (infinitiv) keladi.",
    points: 1,
    difficulty: 1,
    skill: "Vocabulary",
    isActive: true,
  },
];
